# syntax=docker/dockerfile:1
FROM scratch

ADD alpine-minirootfs-3.11.12-x86_64.tar.gz /
RUN /bin/sh
apk add --no-cache --virtual .build-deps bash gcc musl-dev openssl go 
wget -O go.tgz https://dl.google.com/go/go1.10.3.src.tar.gz 

# create docker directory to store the code 
WORKDIR /dockerapp
# copy dependencies to directory 
COPY /app/go.mod /dockerapp/go.mod

# copy source code 
ADD /app /dockerapp/
RUN go mod download
RUN go build -o /docker-go-webapp

# since service runs on 3000 port 
EXPOSE 3000

CMD [ "/docker-go-webapp" ]

